server:
  port: 9009
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//10.99.112.205:1521/scmdb
    username: scm
    password: scm
  redis:
    host: 10.99.112.213
    port: 7021
    pool:
      max-active: 8
  cloud:
    inetutils:
      preferred-networks:
        - 10.99
userTask:
  convert:
    server-name: FAST-AUTH-SERVER
    aip-url: /parse
activiti:
  role:
    key: name
logging:
  file: /opt/jxty/logs/flow-server.log
  level:
    root: warn
    com.len.mapper: debug
    org.activiti.engine.impl.persistence.entity: debug
    ufast: debug